apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
  labels: 
    app: mynginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx
          imagePullPolicy: Always
          image: timmlot/capstone
          ports:
          - containerPort: 80