apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx-deployment
  labels: 
    app: capstone
spec:
  replicas: 2
      spec:
      containers:
        - name: capstone
          imagePullPolicy: Always
          image: timmlot/capstone
          ports:
          - containerPort: 80