apiVersion: v1
kind: Service
metadata:
  name: capstone-deployment
  labels:
    run: capstone-deployment
spec:
  selector:
    run: capstone-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      type: LoadBalancer