apiVersion: v1
kind: Service
metadata:
  name: capstone-deployment
  labels:
    app: capstone
spec:
  selector:
    app: capstone
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer